name: C/C++

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
   
    steps:
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: make
      run: make
    - name: run executable
          ./a.out
