name: C/C++

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
   
    steps:
    - uses: Trass3r/setup-cpp@master
    - name: make
      run: ./a.out
